version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "9001:8000"
    environment:
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - redis
      - minio
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "9002:6379"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio-dev
    ports:
      - "9003:9000"  # API port
      - "9004:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data: